version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL:-http://localhost}
      APP_KEY: ${APP_KEY}
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
      SERVER_MODE: php-fpm
    volumes:
      - storage:/var/www/html/storage
      - cache:/var/www/html/bootstrap/cache
    networks:
      - web

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - app
    expose:
      - "80"
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  storage:
  cache: